"""add permissions to role model

Revision ID: 913814469c9a
Revises: 50f131116a40
Create Date: 2026-07-21 13:34:53.094733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '913814469c9a'
down_revision: Union[str, Sequence[str], None] = '50f131116a40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('can_buy', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('roles', sa.Column('can_message', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('roles', sa.Column('can_ban', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'can_ban')
    op.drop_column('roles', 'can_message')
    op.drop_column('roles', 'can_buy')
    # ### end Alembic commands ###
