name: deploy backend to ACA

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: log in to azure container registry
        uses: azure/docker-login@v1
        with:
          login-server: vstoreacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: build and push docker image
        run: |
          docker build -t vstoreacr.azurecr.io/vstore-backend:${{ github.sha }} .
          docker build -t vstoreacr.azurecr.io/vstore-backend:latest .
          docker push vstoreacr.azurecr.io/vstore-backend:${{ github.sha }}
          docker push vstoreacr.azurecr.io/vstore-backend:latest

      - name: deploy to azure container app
        run: |
          # используем токен, который у тебя уже есть
          export AZURE_ACCESS_TOKEN=${{ secrets.AZURE_ACCESS_TOKEN }}
          
          az containerapp update \
            --name vstore-backend \
            --resource-group vstore-rg \
            --image vstoreacr.azurecr.io/vstore-backend:${{ github.sha }} \
            --subscription 8a6db1d6-57a8-455a-98db-56f175eed6e8